### ISSUE TITLE
Linux服务器初始化设置用户和ssh公私钥登陆 - AirCloud的博客 | AirCloud's Blog

### ISSUE THREAD

**Issue by aircloud** [aircloud/hexo-aircloud-blog#1]
http://niexiaotao.cn/2018/04/11/Linux%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%88%9D%E5%A7%8B%E5%8C%96%E8%AE%BE%E7%BD%AE%E7%94%A8%E6%88%B7%E5%92%8Cssh%E5%85%AC%E7%A7%81%E9%92%A5%E7%99%BB%E9%99%86/

**Comment by chenkehao** [comment]
cool

**Comment by alter1626** [comment]
你好，用了你这套模板，有几个问题想咨询一下

1、怎么更换头像
2、《关于》的文档在哪里编辑

麻烦告知一下，谢谢

**Comment by aircloud** [comment]
头像的话，默认情况下，添加或修改 source/img/avatar.jpg 即可
关于页面，可以参考[这里](https://github.com/aircloud/hexo-theme-aircloud#%E6%A0%87%E7%AD%BE%E9%A1%B5%E9%9D%A2--%E5%85%B3%E4%BA%8E%E9%A1%B5%E9%9D%A2)的说明
