### ISSUE TITLE
主题安装失败

### ISSUE THREAD

**Issue by pingL** [aircloud/hexo-aircloud-blog#14]
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fr1h28tfsaj31kw0yugul.jpg)
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fr1h2bdt5oj31kw177dky.jpg)

**Comment by aircloud** [comment]
我没有太明白你的意思，感觉可能是你的安装方式不太对。
你可以先直接clone本项目，npm i 之后启动，一般应该是没有问题的
