### ISSUE TITLE
友情链接元素没有加载

### ISSUE THREAD

**Issue by mengxiaon** [aircloud/hexo-aircloud-blog#16]
博主，我按照你的那个版本配置好_config.yml中的友情链接了，但是在网页中无法加载出来，不知道为啥，还有希望博主能在左边加个友情链接的页面，由于友链较多，在页脚很不方便，https://mengxiaon.github.io/ 
这个链接是我的博客，数据还没迁到hexo，但是会慢慢转过来的，麻烦博主看下为啥友链不加载，谢谢

**Comment by aircloud** [comment]
你给的这个网址主题貌似不是 Aircloud?
我这边好像没有办法复现问题，你可以把你的配置贴一下
