### ISSUE TITLE
构建利用Proxy和Reflect实现双向数据绑定的微框架 - AirCloud的博客 | AirCloud's Blog

### ISSUE THREAD

**Issue by aircloud** [aircloud/hexo-aircloud-blog#3]
http://niexiaotao.cn/2018/04/09/%E6%9E%84%E5%BB%BA%E5%88%A9%E7%94%A8Proxy%E5%92%8CReflect%E5%AE%9E%E7%8E%B0%E5%8F%8C%E5%90%91%E6%95%B0%E6%8D%AE%E7%BB%91%E5%AE%9A%E7%9A%84%E5%BE%AE%E6%A1%86%E6%9E%B6/

**Comment by langkexiansheng** [comment]
![tim 20180924213524](https://user-images.githubusercontent.com/37947784/45955209-e27c3c00-c041-11e8-90b9-98cd1aa2efa7.png)
![default](https://user-images.githubusercontent.com/37947784/45955210-e27c3c00-c041-11e8-9268-486171c84895.png)
图一是本地的样式，为什么部署到网站上样式变了。变成一条条的线来分割了？

**Comment by aircloud** [comment]
markdown 生成后的内容，实际上你可以理解为是不带样式的 html 标签，你书写 markdown 的应用 对这些标签定义了一些样式。

而这个主题，也针对标签定义了特定的样式，不过这个样式和你用的应用定义的样式不同。

目前看来貌似我这种定义的样式不是很符合你的这种写法... emmm，这个问题我之后可能考虑会调整下

**Comment by langkexiansheng** [comment]
首先谢谢作者回答我这个问题。
由于我的工作主要是安全方面的，对前端的这些页面样式不太懂。
我想问一下，是不是修改主题下面的.css文件就可以了？
