### ISSUE TITLE
自定义内容需要修改的项

### ISSUE THREAD

**Issue by FCarlos13** [aircloud/hexo-aircloud-blog#30]
rt...
自定义的话不知道需要怎么做
希望能出一个说明什么的，谢谢

**Comment by aircloud** [comment]
没太清楚你需要自定义哪些内容，
[这里](https://github.com/aircloud/hexo-theme-aircloud)
有一个基本说明，如果有更多问题，直接回复在本 issue 即可

**Comment by FCarlos13** [comment]
我指的就是需要改成自己的内容的项...
大部分的我试出来了，但是还是有部分不是很明白什么意思或者需不需要改：
1. URL项下的四个值
2. comment下owner和repo两个值
3. donate下的两个值
4.自定义的项是不是就到donate就ok了

额外的问题与反馈：
5.我博客里 关于 的评论区显示的是你博客里的 关于 评论...不知道怎么解决= =
6.主页下方的个人链接的图标在比较少的情况（比如三个）是否可以稍微扩大间距
7.PV和UV有些意义不明，我只知道PV的意思...另外可以考虑把该块和 Created by hexo 块分成两层

**Comment by FCarlos13** [comment]
另外，能不能提供方法去掉 赞赏 这个功能= = 我想写些个人的文章放个 赞赏 有点为难...
以及 head-image放不上去，和另一个issue一样

**Comment by FCarlos13** [comment]
> 另外，能不能提供方法去掉 赞赏 这个功能= = 我想写些个人的文章放个 赞赏 有点为难...
> 以及 head-image放不上去，和另一个issue一样

阿斯顿

**Comment by FCarlos13** [comment]
> 另外，能不能提供方法去掉 赞赏 这个功能= = 我想写些个人的文章放个 赞赏 有点为难...
> 以及 head-image放不上去，和另一个issue一样

帮你找了下问题，不知道是不是，你DEMO版本里_config文件里写的是`header-img: img/home-bg.jpg`，但你img文件夹里并没有home-bg.jpg。。。你可以检查下...

另外刚测试了下，似乎删掉所有文章，deploy过后就变成404 了...是hexo本身的问题吗

**Comment by FCarlos13** [comment]
最后，评论系统似乎有问题
![1](https://user-images.githubusercontent.com/21985863/46103778-4cdcda00-c204-11e8-84f7-569f55eb35f5.png)
点击login后跳出如下提示，以及评论系统如图
![2](https://user-images.githubusercontent.com/21985863/46103832-5fefaa00-c204-11e8-8d4c-52f61c68108d.png)
![3](https://user-images.githubusercontent.com/21985863/46103833-61b96d80-c204-11e8-835c-7c1d4417fa5d.png)

出现了这么多问题，麻烦了...

**Comment by aircloud** [comment]
非常感谢你的问题，我看了下，你提出的问题大部分都是存在的，这个模版自己有一段时间没有更新了，我这两天会针对你提出的问题再更新一遍，预计国庆结束前弄完，然后在这个 issue 里面回复你。

p.s. 这两天工作有点忙，还在赶进度...

**Comment by FCarlos13** [comment]
谢谢www

**Comment by aircloud** [comment]
我大概梳理了下你之前提出的问题，总结如下：

1. 关于底部各类链接自定义的问题，我补充了[文档](https://github.com/aircloud/hexo-theme-aircloud#%E5%BA%95%E9%83%A8%E8%87%AA%E5%AE%9A%E4%B9%89)
2. 关于`donate`的问题，也可以参考[文档](https://github.com/aircloud/hexo-theme-aircloud#%E5%A6%82%E4%BD%95%E5%8F%96%E6%B6%88%E8%B5%9E%E8%B5%8F%E5%8A%9F%E8%83%BD)进行取消
3. 评论的问题，gitment 自身存在一些问题，而且你需要替换key值的，不能直接拿来用的，但是我建议之后使用 [disqus](https://github.com/aircloud/hexo-theme-aircloud#disqus)
4. `header-img`在这个主题实际上没什么用。
5. PV 和 UV 的话，分别是访问人次和独立访问设备数，这应该还是比较通用的词汇，暂时不删除了。
6. 其他提到的一些样式问题，不太影响主流程，而且我目前也没有找到在内容过少的时候特别好的排版方式（增大间距貌似也有点奇怪）, 后续会持续考虑，也欢迎你来提 PR

**Comment by FCarlos13** [comment]
谢谢！基本所有问题都解决了现在。
然后还有个问题想知道，就是设置里这些内容是什么意思
`# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://kaijun.rocks/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:`

**Comment by aircloud** [comment]
这里面的有些配置项，是之前根据 hexo 的能力写上的，也有些是由于某些后期迭代的原因，写上了但是后来没用到，这些冗余配置项可以直接删掉

**Comment by FCarlos13** [comment]
okidoki,谢谢了
