### ISSUE TITLE
我的浏览量没内容

### ISSUE THREAD

**Issue by charmsongo** [aircloud/hexo-aircloud-blog#31]
我文章的浏览量Visit后面没有内容

**Comment by pcwl** [comment]
有遇到同样的问题

**Comment by aircloud** [comment]
这个是因为之使用的浏览量模块换了地址，我已经更新，请更新主题即可

**Comment by pcwl** [comment]
问题有解决，进入 themes/aircloud 目录。执行 git pull origin master
这边的 DEMO 貌似用的还是之前的主题版本，是否可以同步下
