### ISSUE TITLE
index.html生成时是个空文件且0B的大小

### ISSUE THREAD

**Issue by luoqianer** [aircloud/hexo-aircloud-blog#32]
index.html生成时是个空文件且0B的大小，而在git Bash窗口可见WARN  No layout: index.html这样的log信息。

使用的是win7 64bit操作系统。

**Comment by kstwoak** [comment]
> index.html生成时是个空文件且0B的大小，而在git Bash窗口可见WARN No layout: index.html这样的log信息。
> 
> 使用的是win7 64bit操作系统。

我解决了是版本问题。降低一下版本就好了我现在是降到了12
