### ISSUE TITLE
favicon 配置不生效

### ISSUE THREAD

**Issue by pcwl** [aircloud/hexo-aircloud-blog#33]
favicon.png 放入博客根目录的 /source/img 下面，生成网页中无效果。查看public/img文件夹中存在favicon.png

**Comment by aircloud** [comment]
一般来说，你直接放在 source/img 下就可以了，但前提是你没有对相关配置做过改动。

这里我建议你可以先看下[DEMO](https://github.com/aircloud/hexo-aircloud-blog) 尝试一下 DEMO 中的 favicon.ico 是否可以成功显示并且被替换(不是png)。

实际上，在 demo 项目中 favicon 的地址在 `/hexo-aircloud-blog/themes/aircloud/layout/_partial/head.ejs` 中有写到：

```
    <link rel="shortcut icon" href="<%= config.root %>img/favicon.ico">
```

**Comment by pcwl** [comment]
非常感谢，修改模版中文件后缀有解决问题。
