### ISSUE TITLE
评论区只能用那三种吗，感觉好慢

### ISSUE THREAD

**Issue by charmsongo** [aircloud/hexo-aircloud-blog#37]
评论区只能用那gitment，disqus，LiveRe三种吗，感觉好慢

**Comment by small-Teenager** [comment]
评论区怎么添加呢

**Comment by aircloud** [comment]
国内目前的确没有什么好用的。。添加评论区可以参考 项目 [readme](https://github.com/aircloud/hexo-theme-aircloud#%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD)
