### ISSUE TITLE
头像设置失败

### ISSUE THREAD

**Issue by paidaxingNUDT** [aircloud/hexo-aircloud-blog#40]
将_config.yml中sidebar-avatar替换为我的图像链接：
sidebar-avatar: "http://pl06226jn.bkt.clouddn.com/%E6%AD%A6%E6%9E%97%E5%A4%96%E4%BC%A0%E8%A1%A8%E6%83%85%E5%8C%85%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180611194054.png"
效果则是这样，怎么也刷新不出来，图像是可以打开的
![image](https://user-images.githubusercontent.com/37062921/50880112-399ef480-1418-11e9-8634-434c1242ea36.png)
求解答~谢谢

**Comment by leefuyong** [comment]
?同问，还有首页的作者名字是默认的请问在哪里修改

**Comment by paidaxingNUDT** [comment]
> 请问



> ?同问，还有首页的作者名字是默认的请问在哪里修改

author

**Comment by sparkstj** [comment]
看了下sidebar-avatar设置的地址在index.html中会被自动加上/，所以你的地址"http://"其实会变成"/http://"。
不如直接把avatar图片放进public文件夹里面直接调用...
